// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4EpwhfiM3kNX44tS5S3fKRp9d85SrPbI',
    appId: '1:739705735447:web:af8b30447043d036d18f52',
    messagingSenderId: '739705735447',
    projectId: 'post-ee52c',
    authDomain: 'post-ee52c.firebaseapp.com',
    databaseURL: 'https://post-ee52c-default-rtdb.firebaseio.com',
    storageBucket: 'post-ee52c.firebasestorage.app',
    measurementId: 'G-5HGG4K6HC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVoYJzyp-LkNRGmnzZndAaeAH4LqxLN-Q',
    appId: '1:739705735447:android:113cf3de8cd0287ad18f52',
    messagingSenderId: '739705735447',
    projectId: 'post-ee52c',
    databaseURL: 'https://post-ee52c-default-rtdb.firebaseio.com',
    storageBucket: 'post-ee52c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJNf_aWDptCQR5fHocprOEIxk3k4CPz3I',
    appId: '1:739705735447:ios:83230d509ef91646d18f52',
    messagingSenderId: '739705735447',
    projectId: 'post-ee52c',
    databaseURL: 'https://post-ee52c-default-rtdb.firebaseio.com',
    storageBucket: 'post-ee52c.firebasestorage.app',
    iosClientId: '739705735447-s72mndk254c7buuv8o3e74689qib6pr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.postApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJNf_aWDptCQR5fHocprOEIxk3k4CPz3I',
    appId: '1:739705735447:ios:83230d509ef91646d18f52',
    messagingSenderId: '739705735447',
    projectId: 'post-ee52c',
    databaseURL: 'https://post-ee52c-default-rtdb.firebaseio.com',
    storageBucket: 'post-ee52c.firebasestorage.app',
    iosClientId: '739705735447-s72mndk254c7buuv8o3e74689qib6pr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.postApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4EpwhfiM3kNX44tS5S3fKRp9d85SrPbI',
    appId: '1:739705735447:web:bab7c4c8fb64e2e6d18f52',
    messagingSenderId: '739705735447',
    projectId: 'post-ee52c',
    authDomain: 'post-ee52c.firebaseapp.com',
    databaseURL: 'https://post-ee52c-default-rtdb.firebaseio.com',
    storageBucket: 'post-ee52c.firebasestorage.app',
    measurementId: 'G-FBNZMNBTB3',
  );
}
